### ISSUE TITLE
Unhandled Exception in UpdateStreamHeadAsync calling TryMongo

### ISSUE THREAD

**Issue by Hinni** [NEventStore/NEventStore.Persistence.MongoDB#46] opened 2016-09-19 11:11 UTC
We got an issue in the MongoPersistenceEngine. The function “UpdateStreamHeadAsync” does not expect an error in the “TryMongo” at line [516](https://github.com/NEventStore/NEventStore.Persistence.MongoDB/blob/master/src/NEventStore.Persistence.MongoDB/MongoPersistenceEngine.cs#L516), which is possible, after it enters in a seperate thread from the `ThreadPool.QueueUserWorkItem`. The TryMongo is not in the try-catch, what leads to problems if the connection is not available. Obviously it is executed in a separated thread.

Of course we can handle the "unhandled exception", but it's not a good solution.

**Comment by alkampfergit** [comment] 2016-09-20 06:25
It seems a duplicate of #35, you are experiencing this issue even with version  5.3.5 of the driver?

**Comment by Hinni** [comment] 2016-09-20 17:56
@alkampfergit thank you for your response.
No it's not a duplicate. It happens before the try catch. Our connection is sometimes unstable. The TryMongo() fail and an unhandled exception occurs.

**Comment by alkampfergit** [comment] 2016-09-20 19:04
Ok, I'll take a look tomorrow, thanks!

**Closed** 2016-09-22 13:54 UTC

**Comment by Hinni** [comment] 2016-09-29 21:37
Thank you for the quick fix @alkampfergit . When can we get the new 5.3.6 from nuget? Currently there is 5.3.5 the newest version available.

**Comment by alkampfergit** [comment] 2016-09-30 09:31
Published on nuget right now.
